### ISSUE TITLE
100% width

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-chartjs-widget#1]
How can I apply a 100% width to the chart, eg. to take the width from a surrounding bootstrap container?

**Comment by tonydspaniard** [comment]
@schmunk42 Use the `options`, is the one that sets the canvas width: https://github.com/2amigos/yii2-chartjs-widget/blob/master/Chart.php#L79

**Comment by schmunk42** [comment]
Tried it with

```
'options' => [
    'height' => 400,
    'width' => "100%"
],
```

but does not work at least on Safari. Width is only about 50px.

**Comment by tonydspaniard** [comment]
Will have a look

**Comment by tonydspaniard** [comment]
I know this is pretty old, but it seems the library doesn't yet support it: https://github.com/nnnick/Chart.js/issues/882
