### ISSUE TITLE
Use it with Pjax

### ISSUE THREAD

**Issue by ombapit** [2amigos/yii2-chartjs-widget#10]
Hello, can this widget loaded with Pjax feature? i want add a custom filter, so the chart will be changed based on my click button.

Thanks..

**Comment by tonydspaniard** [comment]
@ombapit I am not sure as I have never used it that way, nevertheless, I don't think it should be an issue as long as you rebuild the chart HTML again. You'll have to check the plugin page itself: http://www.chartjs.org/docs/
