### ISSUE TITLE
options in example -> clientOptions

### ISSUE THREAD

**Issue by romdim** [2amigos/yii2-chartjs-widget#11]
options as it is in the example should be clientOptions as it is in the ChartJs.php

**Comment by tonydspaniard** [comment]
Thank you @romdim I'll update asap.

**Comment by tonydspaniard** [comment]
@romdim The example is fine, is the HTML options we set on the example, not the javascript plugin options.

**Comment by krystian-dev548** [comment]
If I run the php example presented on plugin's page NOT WORK. Instead works only with "clientOptions"...
