### ISSUE TITLE
Global chart configuration

### ISSUE THREAD

**Issue by AthmaneKhl** [2amigos/yii2-chartjs-widget#12]
can you set "Chart.defaults.global" ?

**Comment by tonydspaniard** [comment]
@DrokTor Unfortunately, the only way we can do that now is through: https://github.com/2amigos/yii2-chartjs-widget/blob/master/src/ChartJs.php#L92  

And is per chart. Maybe you should consider adding global config on a separate js file?

**Comment by AthmaneKhl** [comment]
Thanks.
