### ISSUE TITLE
chartjs can no longer be installed via bower

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-chartjs-widget#18]
They dropped bower support, see https://github.com/chartjs/Chart.js/commit/c6318749da660f6d8599b466b3871f437123c1d0

I am also creating an issue there.

**Comment by schmunk42** [comment]
You could also switch to `npm`...

**Comment by tonydspaniard** [comment]
it seems stills available for bower

**Comment by schmunk42** [comment]
Fixed in 2.3.0, see https://github.com/chartjs/Chart.js/issues/3033#issuecomment-248721853

You might want to use that as a minimum version in `composer.json` (^2.3.0).

**Comment by tonydspaniard** [comment]
sure... thanks @schmunk42
