### ISSUE TITLE
New version of Chartjs

### ISSUE THREAD

**Issue by eniuz** [2amigos/yii2-chartjs-widget#28]
Hi guys,
Are you planning any updates to chartjs version? The difference is quite big at the moment

**Comment by tonydspaniard** [comment]
Yes! I am going to handle it this weekend if all goes well

**Comment by eniuz** [comment]
Thanks a lot!

**Comment by tonydspaniard** [comment]
done @eniuz

**Comment by eniuz** [comment]
Wicked! Cheers!
