### ISSUE TITLE
I have today this error

### ISSUE THREAD

**Issue by AlessandroCuba** [2amigos/yii2-chartjs-widget#39]
`Setting unknown property: dosamigos\chartjs\ChartJs::plugins` by PieChart

in the Chart class there is no attribute named plugins, but in the documentation there is an example with `"plugins"`.

any idea??

**Comment by RobinJespersen** [comment]
use:
"2amigos/yii2-chartjs-widget": "dev-master",
(There is no release with the "plugins" option so far.)

**Comment by tonydspaniard** [comment]
@AlessandroCuba @RobinJespersen update your version new released [2.1.3](https://github.com/2amigos/yii2-chartjs-widget/tree/2.1.3). Sorry for taking so long.

**Comment by RobinJespersen** [comment]
thx 👍

**Comment by AlessandroCuba** [comment]
thank
