### ISSUE TITLE
No valid bower.json was found in any branch or tag of https://github.com/nnnick/Chart.js.git, could not load a package from it.

### ISSUE THREAD

**Issue by sercon** [2amigos/yii2-chartjs-widget#42]
Getting the error
No valid bower.json was found in any branch or tag of https://github.com/nnnick/Chart.js.git, could not load a package from it.
on composer update.
I think chartjs version 
"bower-asset/chartjs": "~2.6"
as in your composer.json is no longer available from bower. 
https://github.com/chartjs/Chart.js

**Comment by tonydspaniard** [comment]
Thanks... I'll have a look at it.

**Comment by tonydspaniard** [comment]
Updated in version 3
