### ISSUE TITLE
directory to be published does not exist: chartjs/dist

### ISSUE THREAD

**Issue by mrbig00** [2amigos/yii2-chartjs-widget#44]
In the latest release `dev-master` charts js no more includes the `dist` folder, so an error is thrown when using the widget:

`Invalid Argument – yii\base\InvalidArgumentException`
`The file or directory to be published does not exist: /shared/httpd/project/vendor/bower-asset/chartjs/dist`

**Comment by libedux** [comment]
Had to downgrade my version but now it gives "TypeError: (new Chart(...)).bar is not a function" error

**Comment by zertex** [comment]
+1

**Comment by tonydspaniard** [comment]
i'll have a look at it. thanks.

**Comment by tonydspaniard** [comment]
fixed on new version 3.0

**Comment by denostr** [comment]
Run
```composer require nnnick/chartjs "v2.9.3"```

And add to config:
```
'components' => [
    'assetManager' => [
        'bundles' => [
            'dosamigos\chartjs\ChartJsAsset' => [
                'sourcePath' => '@vendor/nnnick/chartjs/dist',
            ],
        ],
    ],
],
```

**Comment by fasi1208** [comment]
> Run
> `composer require nnnick/chartjs "v2.9.3"`
> 
> And add to config:
> 
> ```
> 'components' => [
>     'assetManager' => [
>         'bundles' => [
>             'dosamigos\chartjs\ChartJsAsset' => [
>                 'sourcePath' => '@vendor/nnnick/chartjs/dist',
>             ],
>         ],
>     ],
> ],
> ```

Now it's giving me `Setting read-only property: yii\web\Application::assetManager`

**Comment by denostr** [comment]
@fasi1208 
You must add `assetManager` configuration into `components` section, check it

**Comment by fasi1208** [comment]
> @fasi1208
> You must add `assetManager` configuration into `components` section, check it

Where to add it? means in `composer.json` where to add it ?

**Comment by denostr** [comment]
@fasi1208 In your config file, for example `backend/config/main.php`
For [example](https://gist.github.com/jacksontong/0f872c95f764e0b6dc43#file-main-php-L10)

**Comment by fasi1208** [comment]
> @fasi1208 In your config file, for example `backend/config/main.php`
> For [example](https://gist.github.com/jacksontong/0f872c95f764e0b6dc43#file-main-php-L10)

added now I am getting `Failed to create chart: can't acquire context from the given item` also posted a question at [stack](https://stackoverflow.com/q/61266625/8919244)

**Comment by abreupardom** [comment]
to me work!!! with 2.9.4.


composer require nnnick/chartjs "v2.9.4"

![image](https://user-images.githubusercontent.com/67278221/214905289-ced32c56-8c92-4665-96e7-6d55eb94e41f.png)

![image](https://user-images.githubusercontent.com/67278221/214906007-44314156-7154-43ab-b8b7-8d2984e579f3.png)

![image](https://user-images.githubusercontent.com/67278221/214906097-e94f3e89-0d08-4c28-b41a-f1286ad1fed7.png)


some people know how can use on 4.2.0, the "dist" folder no exist
