### ISSUE TITLE
Chart.js bower version

### ISSUE THREAD

**Issue by fedemotta** [2amigos/yii2-chartjs-widget#5]
Hi,
I need to test some functionalities provided in the master branch of chart.js library. 
As I see in the yii2-chartjs-widget master branch, the composer file it is pointing to a specific release (1.0.2). I think this master branch should be using \* and let the developer decide to specify a version (or not). 
If you make a release of this extension you could use the specified version (or not) but master should be using *. It is the development branch.

What do you think about this approach? Do you think it make sense?

**Comment by tonydspaniard** [comment]
@fedemotta thanks for suggestion. The reason why we decided to forced use of version is due to make sure we do not have BC issues with new releases of the plugin. If you use '*' you probably also have issues with minimum stability issues in composer.

**Comment by fedemotta** [comment]
If you use `*` and your project composer is in stable version it will use the 1.0.2 anyway. If your project is not stable yet it will use the master branch of that library.
There is a `@dev` tag to use instead of `*` to avoid the minimum stability issues if you are in stable version and want a non stable library. 

Also, correct me if I am wrong, with this approach you don't need to update your master branch if a new release of chart.js was made.

**Comment by fedemotta** [comment]
It was a very simple change. Feel free to merge or delete the PR #6

**Comment by creocoder** [comment]
@fedemotta Answered to PR.

**Comment by fedemotta** [comment]
@creocoder @tonydspaniard Please see my comments in the PR. Sorry to bother you!
