### ISSUE TITLE
Cannot Install The Widget

### ISSUE THREAD

**Issue by bxcodec** [2amigos/yii2-chartjs-widget#8]
I got error,  when i tried to Install , this Widget.
# 

 Problem 1
    - Installation request for 2amigos/yii2-chartjs-widget dev-master -> satisfiable by 2amigos/yii2-chartjs-widget[dev-master].
    - 2amigos/yii2-chartjs-widget dev-master requires bower-asset/chartjs 1.0.2 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
# 

How do I solve this problem?

**Comment by ffelaar** [comment]
i have the same problem - did you manage to resolve it?

**Comment by shum16** [comment]
+1

**Comment by trubachoff** [comment]
Solution install as root fxp/composer-asset-plugin
 `sudo composer global require fxp/composer-asset-plugin`

**Comment by tonydspaniard** [comment]
@trubachoff thank  you very much. 

@bxcodec I thought that info is assumed as `Yii2` required that to install: http://www.yiiframework.com/doc-2.0/guide-start-installation.html
