### ISSUE TITLE
Can you change to see legend

### ISSUE THREAD

**Issue by ipppinto** [2amigos/yii2-chartjs-widget#9]
Hi,

In line 96 I put this:
$js .= "document.getElementById('chartLegend_{$id}').innerHTML = chartJS_{$id}.generateLegend();";

and i view this:

<div id="chartLegend_w0"></div>

and I see the legend. Can you do this in your version?

**Comment by tonydspaniard** [comment]
@ipppinto do you mind providing a PR for that? Thanks!

**Comment by tonydspaniard** [comment]
I have updated to latest version, no longer valid ticket.
